INSERT INTO SUBSCRIBER (FIRST_NAME, LAST_NAME, ADRESSE) VALUES ('Mohammed', 'TEBIB', 'Paris, France');
INSERT INTO SUBSCRIBER (FIRST_NAME, LAST_NAME, ADRESSE) VALUES ('Amin', 'TEBIB', 'Lyon, France');
INSERT INTO SUBSCRIBER (FIRST_NAME, LAST_NAME, ADRESSE) VALUES ('Mohammed El Amin', 'TEBIB', 'GrenobleFrance');

