CREATE TABLE SUBSCRIBER {
     ID INTEGER NOT NULL AUTO_INCREMENT,
     FIRST_NAME VARCHAR(255) NOT NULL,
     LAST_NAME  VARCHAR(255) NOT NULL,
     ADRESSE    VARCHAR(255) NOT NULL,
     PRIMARY KEY(ID)
};